pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "us-east-1"
    }
    stages {
        stage("Create an EKS Cluster") {
            steps {
                script {
                    dir('jenkins-deployment/EKS') {
                        sh "terraform init"
                        sh "terraform apply -auto-approve"
                    }
                }
            }
        }
        
        stage("Validate cluster and Create Namespaces") {
            steps {
                script {
                        sh "aws eks update-kubeconfig --name myapp-eks-cluster"
                    }
                }
        }

        // stage("Create Namespaces"){
        //     steps {
        //         script {
        //             // Check if the namespaces already exist
        //             def namespaces = sh(script: 'kubectl get namespace -o jsonpath=\'{.items[*].metadata.name}\'', returnStdout: true).trim()

        //             def sock-shopExists = namespaces.split(" ").contains("sock-shop")
        //             def monitoringExists = namespaces.split(" ").contains("monitoring")
        //             def afeez-portfolioExists = namespaces.split(" ").contains("afeez-portfolio")

        //             if (sock-shopExists && monitoringExists && portfolioExists) {
        //                 // All namespaces already exist, skip the create command
        //                 echo 'All namespaces already exist, skipping create command'
        //             } else {
        //                 // Create namespaces that don't exist
        //                 if (!sockshopExists) {
        //                     sh 'kubectl create namespace sock-shop'
        //                 }
        //                 if (!monitoringExists) {
        //                     sh 'kubectl create namespace monitoring'
        //                 }
        //                 if (!afeez-portfolioExists) {
        //                     sh 'kubectl create namespace afeez-portfolio'
        //                 }
        //             }
        //         }
        //     }
        // }

        stage("Deploy sock-shop to EKS"){
            steps{
                script {
                    dir("jenkins-deployment/manifest-app"){
                        sh "kubectl apply -n sock-shop -f ."
                    }
                }         
            }
        }

        stage("Deploy Monitoring app"){
            steps{
                script {
                    dir("jenkins-deployment/manifests-monitoring"){
                        sh "kubectl apply -n monitoring -f ."
                    }
                }         
            }
        }

        stage("Deploy Portfolio to EKS"){
            steps{
                script {
                    dir("jenkins-deployment/Portfolio"){
                        sh "kubectl apply -n afeez-portfolio -f ."
                    }
                }         
            }
        }

    }
}